//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ao.i_mail.service.tests.i_MailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ao.i_account.service.models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="i_MailService.IMailService")]
    public interface IMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/CreateUser", ReplyAction="http://tempuri.org/IMailService/CreateUserResponse")]
        ao.i_mail.service.tests.i_MailService.User CreateUser(ao.i_mail.service.tests.i_MailService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/CreateUser", ReplyAction="http://tempuri.org/IMailService/CreateUserResponse")]
        System.Threading.Tasks.Task<ao.i_mail.service.tests.i_MailService.User> CreateUserAsync(ao.i_mail.service.tests.i_MailService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/GetUser", ReplyAction="http://tempuri.org/IMailService/GetUserResponse")]
        ao.i_mail.service.tests.i_MailService.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/GetUser", ReplyAction="http://tempuri.org/IMailService/GetUserResponse")]
        System.Threading.Tasks.Task<ao.i_mail.service.tests.i_MailService.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/GetConfig", ReplyAction="http://tempuri.org/IMailService/GetConfigResponse")]
        ao.i_mail.service.data.models.Config GetConfig(ao.i_mail.service.data.models.Config config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/GetConfig", ReplyAction="http://tempuri.org/IMailService/GetConfigResponse")]
        System.Threading.Tasks.Task<ao.i_mail.service.data.models.Config> GetConfigAsync(ao.i_mail.service.data.models.Config config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/CreateConfig", ReplyAction="http://tempuri.org/IMailService/CreateConfigResponse")]
        ao.i_mail.service.data.models.Config CreateConfig(ao.i_mail.service.tests.i_MailService.User user, ao.i_mail.service.data.models.Config config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/CreateConfig", ReplyAction="http://tempuri.org/IMailService/CreateConfigResponse")]
        System.Threading.Tasks.Task<ao.i_mail.service.data.models.Config> CreateConfigAsync(ao.i_mail.service.tests.i_MailService.User user, ao.i_mail.service.data.models.Config config);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServiceChannel : ao.i_mail.service.tests.i_MailService.IMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceClient : System.ServiceModel.ClientBase<ao.i_mail.service.tests.i_MailService.IMailService>, ao.i_mail.service.tests.i_MailService.IMailService {
        
        public MailServiceClient() {
        }
        
        public MailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ao.i_mail.service.tests.i_MailService.User CreateUser(ao.i_mail.service.tests.i_MailService.User user) {
            return base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task<ao.i_mail.service.tests.i_MailService.User> CreateUserAsync(ao.i_mail.service.tests.i_MailService.User user) {
            return base.Channel.CreateUserAsync(user);
        }
        
        public ao.i_mail.service.tests.i_MailService.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<ao.i_mail.service.tests.i_MailService.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public ao.i_mail.service.data.models.Config GetConfig(ao.i_mail.service.data.models.Config config) {
            return base.Channel.GetConfig(config);
        }
        
        public System.Threading.Tasks.Task<ao.i_mail.service.data.models.Config> GetConfigAsync(ao.i_mail.service.data.models.Config config) {
            return base.Channel.GetConfigAsync(config);
        }
        
        public ao.i_mail.service.data.models.Config CreateConfig(ao.i_mail.service.tests.i_MailService.User user, ao.i_mail.service.data.models.Config config) {
            return base.Channel.CreateConfig(user, config);
        }
        
        public System.Threading.Tasks.Task<ao.i_mail.service.data.models.Config> CreateConfigAsync(ao.i_mail.service.tests.i_MailService.User user, ao.i_mail.service.data.models.Config config) {
            return base.Channel.CreateConfigAsync(user, config);
        }
    }
}
